### ISSUE TITLE
Small glitch on specific handle

### ISSUE THREAD

**Issue by Kafkamorph** [mozzius/bsky-team-check#1]
Hi!
Thanks for this, it works great, but on "some" profiles (and I really do not know what is the problem), this happens:

This Serverless Function has timed out.
Your connection is working correctly.
Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
ID: lhr1::bfz65-1683894784126-303126f55501

**Comment by mozzius** [comment]
Hey - if they are being followed by too many people, the API request can take too long so it fails :( I'm not sure it's really solvable unfortunatly

**Comment by Kafkamorph** [comment]
Ahhhhh ok, the account in question has 5.6k followers.

That makes sense now, thanks for your reply.
